SIgnalR+Masstransit Chat
amai-brat/Netflix pull request #56
Opened 2024-10-22 08:51 UTC by GePeKA

1. Не сделал nginx настройку
2. Не добавил support роль в БД пользователей, нужна ли она вообще? Или пусть модераторы тоже людям помогают
3. У каждого пользователя отдельный сеанс его чата поддержки. Id сеанса чата - UserId пользователя. Сразу несколько модераторов или админов могут писать ему в этот чат. 
4. Модераторы, админы могут писать в несколько чатов одновременно
5. Не представляю как протестировать SignalR, видимо только когда будет готов фронт

2024-10-23 20:39 UTC, amai-brat requested changes
конфиг для nginx
```
        location /support/ {
            proxy_pass         http://support-service:8090/;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection $connection_upgrade;
            proxy_set_header   Host $host;
            proxy_http_version 1.1;
            proxy_buffering    off;
            proxy_read_timeout 100s;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
```

2024-10-23 20:39 UTC, amai-brat commented on SupportAPI/Program.cs
> +app.UseAuthentication();
порядок другой

2024-10-23 20:39 UTC, amai-brat commented on compose.prod.yaml
> +      - "8091:8091"
всё равно используется 8080, надо добавить ASPNETCORE_HTTP_PORTS=8090 в environment [link](https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port)

2024-10-23 20:39 UTC, amai-brat commented on SupportAPI/Controllers/HistoryController.cs
> +    }
не хватает метода для supportService.getSupportUsersUnansweredMessagesHistory() с фронта

2024-10-24 08:03 UTC, DmitriyAlexv requested changes

2024-10-24 08:03 UTC, DmitriyAlexv commented on SupportAPI/Data/Entities/SupportChatMessage.cs
> +        public long SenderId { get; set; }
Возможно стоит добавить role и name, либо просто когда надо получать информацию из jwt (Вроде в нём уже всё будет)

2024-10-24 08:46 UTC, amai-brat commented on SupportAPI/Controllers/HistoryController.cs
> +            return Ok(chatHistory);
get в пути излишен, т.к. метод запроса - GET

2024-10-24 12:01 UTC, GePeKA commented on SupportAPI/Controllers/HistoryController.cs
> +    }
Я думаю все таки, если по REST делать, то лучше:
support/chats/unanswered

2024-10-24 12:02 UTC, GePeKA commented on SupportAPI/Controllers/HistoryController.cs
> +        }
Тут тоже по REST думаю лучше:
support/chats/${id}

2024-10-24 12:16 UTC, GePeKA commented on SupportAPI/Controllers/HistoryController.cs
> +    }
Еще не совсем понимаю, зачем нужны messages, если они всегда null

2024-10-24 15:51 UTC, amai-brat commented on SupportAPI/Services/HistoryService.cs
> +            chatSession.ChatMessages!.Add(newChatMessage);
эта строка у тебя не кидает ошибку? chatSession создаётся с null вместо списка

2024-10-25 07:53 UTC, DmitriyAlexv approved these changes

2024-10-25 07:53 UTC, DmitriyAlexv commented on SupportAPI/Controllers/HistoryController.cs
> +            return Ok(await historyService.GetUnansweredChatsAsync());
Нужно ChatMessages перед отправкой сделать null. 
var res = await historyService.GetUnansweredChatsAsync();
res.ForEach((elem) => {elem.ChatMessages = null});
return Ok(res);

2024-10-25 13:59 UTC, amai-brat approved these changes

2024-10-25 14:00 UTC, amai-brat commented on SupportAPI/Services/HistoryService.cs
не понял только этого

2024-10-25 14:07 UTC, GePeKA commented on SupportAPI/Services/HistoryService.cs
Забыл вернуть res) А так, Диме зачем-то на фронте нужно, чтобы ChatMessages были null

2024-10-28 10:38 UTC, DmitriyAlexv commented
Сделай cherry-pick всех коммитов связанных с бэком(названы соотвествующе) из test-sup-chat

2024-10-30 04:20 UTC, merged